language: node_js
node_js:
  - '5'
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  'on':
    branch: src
    node: '5'
env:
  global:
    - secure: >-
        WlL7x7T7ICZpLeqbydg5cb5lwqxkNUGG/2U4ka88tYGW3hJkTg/Sen/Xz7yg6sViKDRswZw5dsp+s+cOHTRiAXuJbdho4FlmftwebV18zJcVo7lHGW3QTD5ROWB2QkY2lyy+RMXf7sApHWMp2IrWyWVH9wRLQRznn1BIqTBhXjrU3KtpXaMfSi02BvCS8o9SIs8qoNVW2hOmDoJdOnrF2hgoRxVfspIDtnqZ/L+2Gbd6jDqqCtbvlM2ToQ07Df+KGk+rhOGfinYHlUoGknyfMOPmK6rNN1If+fUjGbRb22q9lRyiLGd9GbyK8WhLA/RFS+JsS0s52BtqcnmWJC6DbiPjzSCsGUVV4Gf92LDdctJGGn5AS2+AqsD6YvSGtbpDJPL8jZS2npjkhAsNFy4kUK7cBNQ3YBtnNnGwbRK0XDt4+vp4vcnI45istAoqrr0eZe4mJsnTss+B/Sgn2sGTohp7dgK6nscnoUX7WV+dSYfqnaDtRMyJjrVm6tNuyO3aI4ONhtnFATH0uPyiQrzZCNWR0ifCfOAtPvo/8yv7kCDg9y56THg5gOM4X2iohv2u0HeeIYj9PFKsBArCH9HfTtJ2zKP/7TEQAvsj2BXzJI76B/Nmgmm4YVN3hI8ZYXOiAqngT0iUwQlcsL151JQx2UCqAXFWCniDZv/SEEFOZQ0=
    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/xuopled/ced.photo.github.io.git
before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - >-
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee
    /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install: yarn
notifications:
  email:
    recipients:
      - xuopled@gmail.com
    on_success: change
    on_failure: always
